### ISSUE TITLE
ExpressionBuiler

### ISSUE THREAD

**Issue by ghost** [Aleksandr185/MathExpressions#1]
Как мне использовать ExpressionBuilder::exec(), чтобы отобразить его на экране? Точнее говоря, как мне сделать что-то подобное:
`...`
`MathExpressions::ExpressionBuilder builder;`
`this->ui.layout->addWidget(builder.exec("y=root(3, x-1)"));`
`...`
И еще вопрос, есть ли возможность, как-то прикрутить курсор (чтобы видеть его позицию в выражении) к выражению?
Если да, то с чего стоит начать?

**Comment by Aleksandr185** [comment]
ExpressionBuilder::exec() возвращает std::unique_ptr<AbstractExpression>.
AbstractExpression не является наследником QWidget, поэтому его нельзя добавить в QLayout. Его можно отобразить на QWidget в функции QWidget::paintEvent(посмотри demo проект, expression_widget.cpp) или на любом наследнике QPaintDevice (QPrinter, QPixmap, QPicture и т.д.)
Для курсора нужно писать наследника AbstractExpression и я думаю это будет достаточно сложно.

**Comment by U1ght** [comment]
Спасибо, за ответ! У меня есть еще один вопрос. Есть ли способ оставить лишние нули в десятичном дроби, чтобы не было подобного?
![image](https://user-images.githubusercontent.com/102179501/204108085-f3fae8e6-35f2-4a9f-ba0d-5c07f10603bd.png)

**Comment by Aleksandr185** [comment]
Если для ExpressionBuilder::exec(), то функция num(R, n1, n2, n3). Если программно, то класс ExtendedNumberExpresssion(double number, int precision, int decimals, int maxDegree).
precision или n1 - это до скольких знаков, после запятой, будет выполняться округление.
decimals или n2 - это количество знаков, которое будет в итоге выведено после запятой.

но иногда оно немного странно работает и всегда обрезает нули в конце.

**Comment by U1ght** [comment]
> Если для ExpressionBuilder::exec(), то функция num(R, n1, n2, n3). Если программно, то класс ExtendedNumberExpresssion(double number, int precision, int decimals, int maxDegree).
> 
> precision или n1 - это до скольких знаков, после запятой, будет выполняться округление.
> 
> decimals или n2 - это количество знаков, которое будет в итоге выведено после запятой.
> 
> 
> 
> но иногда оно немного странно работает и всегда обрезает нули в конце.

**Comment by U1ght** [comment]
А как мне использовать num(R, n1, n2,n3), я нашел только ExpressionBuilder::functionNUM(), но она является приватной, как мне использовать ExpressionBuilder::exec() вместе с num(R,n1,n2,n3)

**Comment by Aleksandr185** [comment]
ExpressionBuilder::exec() принимает в качестве аргумента строку с описанием функции и по этому описанию строит дерево математического выражения и возвращает указатель на корень этого дерева. Это удобно, если нужно хранить формулу где нибудь(например в файле или базе данных) или заранее неизвестно какая нужна формула. 
Тот же результат можно достичь построив дерево вручную использую потомков класса AbstractExpression.
ExpressionBuilder::exec(QString("num(1.12005263, 4, 4)")) - напиши так, для варианта ExpressionBuilder.
new ExtendedNumberExpresssion(1.12005263, 4, 4) - для построения вручную.
